server:
  port: 7003

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  elasticsearch:
    rest:
      uris: http://192.168.6.66:9200

logging:
  level:
    tracer: trace
    org.elasticsearch: trace