#application.yml配置文件优先级低，项目刚启动时不能读取

server:
  port: 80

#配置链路追踪的地址
spring:
  zipkin:
    base-url: http://192.168.6.66:9411/
    sender:
      type: web
  cloud:
    gateway:
      globalcors:   #跨域配置
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
      # 路由规则
      routes:
        - id: product_route   # 路由名称
          uri: lb://service-product   # lb负载均衡转给service-product服务名
          predicates:
            - Path=/admin/product/**  # 路径断言：