#application.yml配置文件优先级低，项目刚启动时不能读取

server:
  port: 80

spring:
  #Redis参数配置
  redis:
    host: 192.168.6.66
    port: 6379
    password: MWc123456

  zipkin: #配置链路追踪的地址
    base-url: http://192.168.6.66:9411/
    sender:
      type: web

  cloud:
    gateway:  #网关配置

      globalcors:   #跨域配置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许其他源跨域访问
            allowedMethods: "*" #允许其他请求方式跨域访问
            allowedHeaders: "*" #允许其他请求头跨域访问
            allowCredentials: true #允许携带其他证书跨域访问

      routes: #路由规则
        - id: product_route   # 路由名称
          uri: lb://service-product   # lb负载均衡转给service-product服务名
          predicates:
            - Path=/admin/product/**  # 路径断言：

        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**  # 路径断言：

        - id: cart_route
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**  # 路径断言：

        - id: web_all_route
          uri: lb://web-all
          predicates:
          - Host=**.gmall.com  # Host断言：

app:
  auth:
    no-auth-url:
      - /css/**
      - /img/**
      - /js/**
      - /login.html
      - /api/user/passport/login
    login-auth-url:
      - /order/**

    deny-auth-url:
      - /api/inner/rpc/**
    login-page: http://passport.gmall.com/login.html