#application.yml配置文件优先级低，项目刚启动时不能读取

server:
  port: 7001
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


  #配置链路追踪的地址
  zipkin:
    base-url: http://192.168.6.66:9411/
    sender:
      type: web

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义配置
