server:
  port: 7005

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#订单信息全部存储在redis中，配置已有nacos统一管理

#自定义配置
app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300 #单位秒