server:
  port: 7002

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#自定义配置
app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300 #单位秒
management:
  endpoints:
    web:
      exposure:
        include: "*"
#线程池监控端口