#application.yml配置文件优先级低，项目刚启动时不能读取

server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://192.168.6.66:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#配置链路追踪的地址
  zipkin:
    base-url: http://192.168.6.66:9411/
    sender:
      type: web

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl